# Generated by Django 4.1.5 on 2026-03-30 20:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("apps_sth", "0002_alter_stage_options_alter_stage_table"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="stage",
            options={},
        ),
        migrations.AlterModelTable(
            name="stage",
            table=None,
        ),
    ]
