# Generated by Django 4.1.5 on 2026-04-14 00:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("apps_sth", "0003_alter_stage_options_alter_stage_table"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="stage",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelTable(
            name="stage",
            table="sth_stage",
        ),
    ]
