# Generated by Django 4.1.5 on 2026-03-30 20:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("apps_employee", "0004_alter_sthstageexperiencelevel_table"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="sthstageexperiencelevel",
            table=None,
        ),
    ]
