# Generated by Django 4.1.5 on 2026-03-30 21:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("apps_employee", "0006_employeeorganizationmembership_employee_user_and_more"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="employeeorganizationmembership",
            new_name="employee_or_employe_a918e8_idx",
            old_name="employee_or_employe_0ea258_idx",
        ),
        migrations.RenameIndex(
            model_name="employeeorganizationmembership",
            new_name="employee_or_employe_06d11d_idx",
            old_name="employee_or_employe_81831d_idx",
        ),
        migrations.RenameIndex(
            model_name="employeeorganizationmembership",
            new_name="employee_or_organiz_e1ed0e_idx",
            old_name="employee_or_organiz_619738_idx",
        ),
    ]
