# Generated by Django 4.1.5 on 2026-04-02 21:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "apps_employee",
            "0008_employeeorganizationmembership_employee_single_active_primary_membership",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employee",
            name="organizations",
        ),
        migrations.RemoveField(
            model_name="employee",
            name="user",
        ),
        migrations.DeleteModel(
            name="EmployeeOrganizationMembership",
        ),
    ]
