# Generated by Django 4.1.5 on 2026-04-14 00:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "apps_employee",
            "0009_remove_employee_organizations_remove_employee_user_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelTable(
            name="sthstageexperiencelevel",
            table="sth_stage_experience_level",
        ),
    ]
