# Generated by Django 4.1.5 on 2026-03-30 20:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apps_questionnaire", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="questionnaire",
            name="document",
            field=models.FileField(
                blank=True, null=True, upload_to="documents/%Y/%m/%d/"
            ),
        ),
        migrations.AlterModelTable(
            name="adoptedlevel",
            table="adopted_level",
        ),
        migrations.AlterModelTable(
            name="answer",
            table="answer",
        ),
        migrations.AlterModelTable(
            name="questionnaire",
            table="questionnaire",
        ),
        migrations.AlterModelTable(
            name="statement",
            table="statement",
        ),
    ]
