# Generated by Django 4.1.5 on 2026-03-30 20:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("apps_questionnaire", "0003_alter_questionnaire_document_and_more"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="adoptedlevel",
            table=None,
        ),
        migrations.AlterModelTable(
            name="answer",
            table=None,
        ),
        migrations.AlterModelTable(
            name="questionnaire",
            table=None,
        ),
        migrations.AlterModelTable(
            name="statement",
            table=None,
        ),
    ]
