# Generated by Django 4.1.5 on 2026-03-21 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("apps_organization", "0001_initial"),
        (
            "apps_questionnaire",
            "0004_alter_adoptedlevel_table_alter_answer_table_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="questionnaire",
            name="organization_questionnaire",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questionnaire_questionnaire_%(class)s",
                to="apps_organization.organization",
            ),
        ),
    ]
