# Generated by Django 4.1.5 on 2026-04-22 22:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("apps_organization", "0004_alter_region_options_alter_state_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="organization",
            name="organization_sector",
        ),
        migrations.RemoveField(
            model_name="organization",
            name="target_audience",
        ),
        migrations.RemoveField(
            model_name="organization",
            name="years_experience_range",
        ),
    ]
