# Generated by Django 4.1.5 on 2026-04-22 22:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apps_organization", "0005_remove_organization_organization_sector_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="organization_sector",
            field=models.CharField(
                blank=True, help_text="organization sector", max_length=200, null=True
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="target_audience",
            field=models.CharField(
                blank=True,
                help_text="organization target audience",
                max_length=200,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="years_experience_range",
            field=models.CharField(
                blank=True,
                help_text="organization years of software development experience",
                max_length=50,
                null=True,
            ),
        ),
    ]
