# Generated by Django 4.1.5 on 2026-03-30 20:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "apps_practitionerseye",
            "0002_alter_element_options_alter_category_table_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="element",
            options={},
        ),
        migrations.AlterModelTable(
            name="category",
            table=None,
        ),
        migrations.AlterModelTable(
            name="element",
            table=None,
        ),
    ]
