# Generated by Django 4.1.5 on 2026-04-14 00:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "apps_practitionerseye",
            "0003_alter_element_options_alter_category_table_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="element",
            options={"ordering": ["dimension__name", "name"]},
        ),
        migrations.AlterModelTable(
            name="category",
            table="practitioners_eye_category",
        ),
        migrations.AlterModelTable(
            name="element",
            table="practitioners_eye_element",
        ),
    ]
